# Dockerfile dump
# sudo apt install software-properties-common
# sudo add-apt-repository ppa:ondrej/php
# sudo apt update
# sudo apt install php7.4
# php -v

version: "3.7"
networks:
  mynet:

volumes:
  mysql_data:
  phpmyadmin_data:
services:
  #
  # MYSQL DB (seeded via repo)
  #------------------------------
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=800_docker
      - MYSQL_USER=800_docker
      - MYSQL_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    networks:
      - mynet

  #
  # PHP MyADMIN
  #--------------
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    networks:
      - mynet
    depends_on:
      - mysql

  #
  # WEB SERVER
  #--------------
  www:
    # use search at https://hub.docker.com/
    image: php:apache
    # sync FOLDER with WEB FOLDER
    volumes:
      # ./local/path/:/WEB/PATH
      - "./public/:/var/www/html"
    ports:
      - 80:80
      - 443:443
    networks:
      - mynet
    depends_on:
      - mysql
      - phpmyadmin
